name: ChaosUtils
version: 2.0
main: com.scuph.scuphutils.ScuphUtils
description: Utility plugin!
authors: [Scuph, Prozza]
commands:
    information:
        usage: /<command>
        description: Info about the plugin and server
        aliases: []
        permission: utils.info
    forums:
        usage: /<command>
        description: the forums link
        aliases: [website]
        permission: utils.forums  
    requesthelp:
        usage: /<command>
        description: request help
        aliases: [helpme]
        permission: utils.requesthelp
    warn:
        usage: /<command>
        description: warn a player
        aliases: []
        permission: utils.warn
    
    